Break down dense lines
ref #6

Wrap long, dense lines to reduce future VCS churn and make it clearer
what's happening.

diff --git a/nvi b/nvi
--- a/nvi
+++ b/nvi
@@ -102,22 +102,50 @@ function install_node() {
   # Download and extract the tar if it doesn't exist on disk.
   if [[ ! -d "$INSTALL_DIR/node-v$NODE_VERSION-linux-x64" ]]; then
     # Fail if version doesn't exist.
-    NODE_DIST_LOOKUP=$(wget -qO - https://nodejs.org/dist/index.json | grep --null-data --only-matching --perl-regex --text "\"version\"\s*:\s*\"v$NODE_VERSION\"")
-    [[ -z "$NODE_DIST_LOOKUP" ]] && >&2 echo "Error: Couldn't find Node.js version v$NODE_VERSION. Aborting." && exit 1
+    local NODE_DIST_LOOKUP
+    NODE_DIST_LOOKUP=$(wget -qO - https://nodejs.org/dist/index.json |
+    grep \
+      --null-data \
+      --only-matching \
+      --perl-regex "\"version\"\s*:\s*\"v$NODE_VERSION\"" \
+      --text
+    )
+    [[ -z "$NODE_DIST_LOOKUP" ]] &&
+      >&2 echo "Error: Couldn't find Node.js version v$NODE_VERSION. Aborting." &&
+      exit 1
     # Download and extract it if it does.
     NODE_TAR="https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz"
-    if ! wget --output-document="$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" --quiet "$NODE_TAR"; then
-      >&2 echo "Error: Couldn't download $NODE_TAR to ${PWD}/$NODE_VERSION.tar.gz, but the version is valid. Possibly a network or permission issue. Aborting." && exit 1
+    if ! wget \
+      --output-document="$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" \
+      --quiet \
+      "$NODE_TAR"
+    then
+      >&2 echo "Error: Couldn't download $NODE_TAR to ${PWD}/$NODE_VERSION.tar.gz, but the version is valid. Possibly a network or permission issue. Aborting."
+      exit 1
     fi
-    tar --extract --file "$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" --gzip --directory "$INSTALL_DIR"
+    tar \
+      --extract \
+      --file \
+      "$DOWNLOAD_DIR/$NODE_VERSION.tar.gz" \
+      --gzip \
+      --directory \
+      "$INSTALL_DIR"
     rm -- "$DOWNLOAD_DIR/$NODE_VERSION.tar.gz"
     # If the download dir was created by us and is now empty, remove it.
-    [[ ! -z $FRESH_DOWNLOAD_DIR ]] && [[ -z "$(ls -A "$DOWNLOAD_DIR")" ]] && rm -d -- "$DOWNLOAD_DIR"
+    [[ ! -z $FRESH_DOWNLOAD_DIR ]] &&
+      [[ -z "$(ls -A "$DOWNLOAD_DIR")" ]] &&
+      rm -d -- "$DOWNLOAD_DIR"
   fi
 
   # Install executables in the bin dir.
   cp -- "$INSTALL_DIR/node-v$NODE_VERSION-linux-x64/bin/node" "$BIN_DIR/node"
-  ln --force --symbolic -- "$(readlink --canonicalize "$INSTALL_DIR/node-v$NODE_VERSION-linux-x64/bin/npm")" "$BIN_DIR/npm"
+  ln \
+    --force \
+    --symbolic \
+    -- \
+    "$(readlink --canonicalize \
+    "$INSTALL_DIR/node-v$NODE_VERSION-linux-x64/bin/npm")" \
+    "$BIN_DIR/npm"
 }
 
 function argument_parser() {
@@ -169,7 +197,13 @@ function argument_parser() {
       >&2 echo "Error: Trying to infer the Node.js version from a package.json file, but ${PWD}/package.json doesn't exist."
       exit 1
     fi
-    PACKAGE_JSON_VERSION=$(grep --null-data --only-matching --perl-regex --text '"engines":\s*{\s*"node":\s*"\K[^"]*' ./package.json)
+    PACKAGE_JSON_VERSION=$(grep \
+      --null-data \
+      --only-matching \
+      --perl-regex \
+      --text \
+      '"engines":\s*{\s*"node":\s*"\K[^"]*' \
+      ./package.json)
     if [[ $PACKAGE_JSON_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
       NODE_VERSION=$PACKAGE_JSON_VERSION
     else
